global:
  scrape_interval: 5s

scrape_configs:
  - job_name: order-producer
    static_configs:
      - targets: ["order-producer:9101"]

  - job_name: payment-producer
    static_configs:
      - targets: ["payment-producer:9102"]

  - job_name: dq-gate
    static_configs:
      - targets: ["dq-gate:9104"]

  - job_name: stream-processor
    static_configs:
      - targets: ["stream-processor:9105"]
